
pipeline{
	agent any
	stages {

		stage('Git clone') {
            steps() {
                git branch: 'main'
				url: 'https://github.com/nimo-my/SWProj.git'
            }
        }

		stage('Checkout') {
			steps {
			// 소스코드 체크아웃 
			checkout scm
			} 
		}

		stage('Build') { 
			steps {
				
				// mac code here

				// windows code here

				}
			echo "Build finished!!! :D"
			}
		}


		stage('Test01 - BookTest (JUnit test)') { 
			steps {
				script{

				
				// mac code here

				// windows code here

				} 
				echo "Test01 finished!!! :D"
			}
		}

		stage('Test02 - Performance Test (in main function)') { 
			steps {
				script{
				
				// mac code here

				// windows code here
				
				}
				echo "Test02 finished!!! :D"
			}
		}
	}
	post {
		always{
			archiveArtifacts 'test_results.txt'
		// success {
		// echo 'Build and test succeeded'
		// } 
	}
		
}


